In [43]:
import torch
import numpy as np
import pandas

### initializing an empty torch tensor

In [16]:
x = torch.empty(4, 2,2,3) ## arguments are the tensor dimension

### initialize a random tensor

In [19]:
x = torch.rand(2,2)

In [20]:
print(x)

tensor([[0.2591, 0.7126],
        [0.6716, 0.5303]])


### initialize a tensor with zeros or ones

In [22]:
x = torch.zeros(2,2)

In [27]:
y = torch.ones(2,2)

In [29]:
x.dtype

torch.float32

In [33]:
x1 = torch.ones(2,2, dtype=torch.float16)
x2 = torch.ones(2,2, dtype=torch.double)
x3 = torch.ones(2,2, dtype=torch.int)

### create an arbitrary tensor

In [52]:
x = torch.tensor(np.array([1,2,3,4]), dtype=torch.float32)

In [53]:
x.dtype

torch.float32

## tensor operations

### addition

In [63]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [64]:
z =  x + y

In [67]:
z = torch.add(x,y)

In [68]:
## in place addition. In general , inplace methods have _

In [70]:
y.add_(x)

tensor([[1.0529, 1.3603],
        [1.0493, 1.3726]])

In [71]:
y

tensor([[1.0529, 1.3603],
        [1.0493, 1.3726]])

### subtraction

In [73]:
z = x - y

In [74]:
z = torch.sub(x,y)

In [75]:
y.sub_(x)

tensor([[0.7638, 0.5803],
        [0.4593, 0.5971]])

### multiplication (element wise)

In [77]:
z = x*y

In [78]:
z = torch.mul(x,y)

In [79]:
y.mul_(x)

tensor([[0.2209, 0.4526],
        [0.2710, 0.4631]])

In [80]:
z

tensor([[0.2209, 0.4526],
        [0.2710, 0.4631]])

### division (element wise)

In [82]:
z = x/y

In [83]:
z = torch.div(x,y)

In [84]:
y.div_(x)

tensor([[0.7638, 0.5803],
        [0.4593, 0.5971]])

## slices

In [86]:
x = torch.rand(5,3)

In [93]:
(x[1,0:2]).shape

torch.Size([2])

### to get a single value, use item

In [96]:
x[0,0].item()

0.9592262506484985

## reshaping a tensor, use view

In [98]:
x = torch.rand(4,4)

In [100]:
x

tensor([[0.4919, 0.1724, 0.0352, 0.2832],
        [0.4719, 0.0417, 0.3032, 0.2878],
        [0.4261, 0.4662, 0.3530, 0.2121],
        [0.2219, 0.2053, 0.0251, 0.7438]])

In [105]:
x.view(16).shape

torch.Size([16])

#### you don't need to specify both dimensions, specify one dimension, and put -1, pytorch automatically figures other dimension out


In [106]:
x.view(8,-1)

tensor([[0.4919, 0.1724],
        [0.0352, 0.2832],
        [0.4719, 0.0417],
        [0.3032, 0.2878],
        [0.4261, 0.4662],
        [0.3530, 0.2121],
        [0.2219, 0.2053],
        [0.0251, 0.7438]])

In [107]:
x.view(7,-1)

RuntimeError: shape '[7, -1]' is invalid for input of size 16

## numpy to torch and vice versa

In [109]:
a = torch.ones(5)

In [111]:
b = a.numpy()

In [112]:
print(b)

[1. 1. 1. 1. 1.]


In [116]:
type(a.dtype)

torch.dtype

In [117]:
## Note that both share same memory location

In [118]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [119]:
a

tensor([2., 2., 2., 2., 2.])

In [120]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [121]:
## numpy to torch

In [122]:
a = np.ones(5)

In [123]:
a

array([1., 1., 1., 1., 1.])

In [124]:
b = torch.from_numpy(a)

In [125]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [127]:
a[0] = 5

In [128]:
a

array([5., 1., 1., 1., 1.])

In [129]:
print(b)

tensor([5., 1., 1., 1., 1.], dtype=torch.float64)


In [130]:
torch.cuda.is_available()

False

In [131]:
## note that if gpu is available, numpy is not present on gpu
## so you have to do device carefully

In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device) ## creates x on gpu. You can either use this format or format below
    y = torch.ones(5)
    y = y.to(device)
    z = x + y ## z now resides on gpu
    ## can't to z.numpy() as numpy doesn't work on gpu
    z = z.to("cpu").numpy() ## first port to cpu and then do numpy
    

## If you want to take grad on tensor, you have to use requires_grad = True

In [132]:
x = torch.ones(5,2, requires_grad=True)

## References
